# -*- coding: utf-8 -*-
# topic_6_transfer_study.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1RivaPbGOsHKjpFjj8uyA2Aog6hwcagqp

# Transfer Study from Conspect information


import warnings
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import torch.backends.cudnn as cudnn
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
from PIL import Image
from tempfile import TemporaryDirectory

# Enables the inbuilt cudnn auto-tuner to find the best algorithm to use for your hardware.
# Effective when input sizes for the network do not vary.
cudnn.benchmark = True

plt.ion()   # interactive mode

# filter warnings
warnings.filterwarnings('ignore')

# """Опишемо навчальну й тестову аугментації."""

data_transforms = {
    'train': transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

# """Створимо клас Dataset."""

data_dir = './Module_3_Topic_6_hymenoptera_data'

image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x),
                                          data_transforms[x])
                  for x in ['train', 'val']}

# """Створимо клас DataLoader."""

dataloaders = {x: torch.utils.data.DataLoader(image_datasets[x], batch_size=4,
                                              shuffle=True, num_workers=0)
               for x in ['train', 'val']}

# """Збережемо інформацію про розмір датасету та назви класів."""

dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes

print(dataset_sizes)
print(class_names)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# """Створимо функцію для відображення прикладів."""


def imshow(inp, title=None):
    inp = inp.numpy().transpose((1, 2, 0))
    mean = np.array([0.485, 0.456, 0.406])  # Imagenet mean
    std = np.array([0.229, 0.224, 0.225])  # Imagenet std
    inp = std * inp + mean
    inp = np.clip(inp, 0, 1)
    plt.imshow(inp)
    if title is not None:
        plt.title(title)
    plt.pause(0.001)  # pause a bit so that plots are updated

# """Візуалізуємо один батч даних."""


# Get a batch of training data
inputs, classes = next(iter(dataloaders['train']))

# Make a grid from batch
out = torchvision.utils.make_grid(inputs)

imshow(out, title=[class_names[x] for x in classes])

# """Напишемо загальну функцію train_model, яка буде виконувати навчання й валідацію моделі протягом num_epochs. Кінцевим результатом роботи функції буде модель, що показала найвищу точність на валідації."""


def train_model(model, criterion, optimizer, scheduler, num_epochs=25):
    since = time.time()

    # Create a temporary directory to save training checkpoints
    with TemporaryDirectory() as tempdir:
        best_model_params_path = os.path.join(tempdir, 'best_model_params.pt')

        # save model
        torch.save(model.state_dict(), best_model_params_path)
        best_acc = 0.0

        for epoch in range(num_epochs):
            print(f'Epoch {epoch+1}/{num_epochs}')
            print('-' * 10)

            # Each epoch has a training and validation phase
            for phase in ['train', 'val']:
                if phase == 'train':
                    model.train()  # Set model to training mode
                else:
                    model.eval()   # Set model to evaluate mode

                running_loss = 0.0
                running_corrects = 0

                # Iterate over data.
                for inputs, labels in dataloaders[phase]:
                    inputs = inputs.to(device)
                    labels = labels.to(device)

                    # zero the parameter gradients
                    optimizer.zero_grad()

                    # forward
                    # track history if only in train
                    with torch.set_grad_enabled(phase == 'train'):
                        outputs = model(inputs)
                        _, preds = torch.max(outputs, 1)
                        loss = criterion(outputs, labels)

                        # backward + optimize only if in training phase
                        if phase == 'train':
                            loss.backward()
                            optimizer.step()
                            scheduler.step()

                    # statistics
                    running_loss += loss.item() * inputs.size(0)
                    running_corrects += (preds == labels).sum().item()

                epoch_loss = running_loss / dataset_sizes[phase]
                epoch_acc = running_corrects / dataset_sizes[phase]

                print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}')

                # deep copy the model
                if phase == 'val' and epoch_acc > best_acc:
                    best_acc = epoch_acc
                    torch.save(model.state_dict(), best_model_params_path)

            print()

        time_elapsed = time.time() - since
        print(
            f'Training complete in {time_elapsed // 60:.0f}m {time_elapsed % 60:.0f}s')
        print(f'Best val Acc: {best_acc:4f}')

        # load best model weights
        model.load_state_dict(torch.load(best_model_params_path))
    return model

# """Також створимо функцію для візуалізації результатів."""


def visualize_model(model, num_images=6):
    was_training = model.training
    model.eval()
    images_so_far = 0
    fig = plt.figure()

    with torch.no_grad():
        for i, (inputs, labels) in enumerate(dataloaders['val']):
            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            for j in range(inputs.size()[0]):
                images_so_far += 1
                ax = plt.subplot(num_images//2, 2, images_so_far)
                ax.axis('off')
                ax.set_title(
                    f'predicted: {class_names[preds[j]]}, true: {class_names[labels[j]]}')
                imshow(inputs.cpu().data[j])

                if images_so_far == num_images:
                    model.train(mode=was_training)
                    return
        model.train(mode=was_training)

# """***Навчання всіх ваг моделі***

# Завантажимо претреновані ваги моделі ResNet.
# У параметрі weights зазначимо посилання на набір даних ImageNet.


model_ft = models.resnet18(weights='IMAGENET1K_V1')

# """Нам потрібно встановити останній fully-connected шар лінійним шаром, який на виході матиме кількість нейронів, рівну кількості класів моделі."""

num_ftrs = model_ft.fc.in_features
model_ft.fc = nn.Linear(num_ftrs, 2)

# """Переведемо модель на доступний обчислювальний пристрій — CPU або GPU."""

model_ft = model_ft.to(device)

# """*функцією втрат буде CrossEntropyLoss.*"""

criterion = nn.CrossEntropyLoss()

# """***У якості алгоритму оптимізації вистачить SGD.*** ???????? чому далі вказано Adam"""

optimizer_ft = optim.Adam(model_ft.parameters(), lr=1e-05)

# """# Експоненціальне зменшення learning rate"""

exp_lr_scheduler = lr_scheduler.ExponentialLR(optimizer_ft, gamma=0.9)

# """Виконаємо навчання моделі протягом 5 епох. Результати тренування надрукуємо в консоль."""


model_ft = train_model(model_ft, criterion, optimizer_ft,
                       exp_lr_scheduler, num_epochs=5)


print()
print('Нове навчання')
print()


# ***Навчання тільки класифікаційного шару***

# Тепер виконаємо тренування тільки класифікаційного шару. Усі інші ваги моделі будуть «заморожені» (frozen) — тобто для ваг цих шарів ми не будемо розраховувати градієнти й виконувати процедуру оновлення ваг.

# ***Для початку знову завантажимо модель ResNet18, претреновану на датасеті ImageNet.***

model_conv = torchvision.models.resnet18(weights='IMAGENET1K_V1')

# """***Тепер для всіх параметрів моделі встановимо параметр requires_grad = False ***"""

for param in model_conv.parameters():
    param.requires_grad = False

# """Тепер додамо класифікаційний шар. Параметри новостворених шарів за замовчуванням мають requires_grad = True."""

num_ftrs = model_conv.fc.in_features
model_conv.fc = nn.Linear(num_ftrs, 2)

model_conv = model_conv.to(device)

criterion = nn.CrossEntropyLoss()

optimizer_conv = optim.Adam(model_conv.fc.parameters(), lr=1e-03)

# Експоненціальне зменшення learning rate
exp_lr_scheduler = lr_scheduler.ExponentialLR(optimizer_conv, gamma=0.9)

# """Повторимо тренування моделі."""

model_conv = train_model(model_conv, criterion,
                         optimizer_conv, exp_lr_scheduler, num_epochs=5)

# """Візуалізуємо результати для замороженої моделі."""

visualize_model(model_conv)
